function getQVar(a,c){for(var b=c.split("&"),d=0;d<b.length;d++){var e=b[d].split("=");if(e[0]==a)return e[1]}return""}function genuid(){var a="",c,b;for(b=0;32>b;b++){if(8==b||12==b||16==b||20==b)a+="-";c=Math.floor(16*Math.random()).toString(16).toUpperCase();a+=c}return a}function jsetck(a){var c=getCkExpDays(jcexpire),b=getwdom();document.cookie=jckName+"="+escape(a)+(c?";expires="+c.toGMTString():"")+";path=/"+(b?";domain="+b:"")}
function jgetck(a){var c=document.cookie;a+="=";var b=c.indexOf(a);if(-1==b)return null;var d=document.cookie.indexOf(";",b);-1==d&&(d=c.length);return unescape(c.substring(b+a.length,d))}function getCkExpDays(a){if(null==a||"null"==a||""==a)a="30";if("0"==a||0==a)return null;var c=new Date;c.setDate(c.getDate()+parseInt(a));return c}
function getwdom(){var a=window.location.hostname.split("."),c="";return c=2!=a[a.length-1].length||2!=a[a.length-2].length&&3!=a[a.length-2].length?"."+a[a.length-2]+"."+a[a.length-1]:"."+a[a.length-3]+"."+a[a.length-2]+"."+a[a.length-1]}function useCustomParams(){jCustParam=!0}function trackSEO(a){null!=a&&void 0!=a&&(jSEOName=a);jtrkOrg=!0}function trackDirectTraffic(a){null!=a&&void 0!=a&&(jDirCampName=a);jtrkDir=!0}
function recordJSConversion(a,c,b,d,e,m){var f="http";"https:"==window.location.protocol&&(f="https");var f=f+track_URL,g=""+jgetck(jckName),l=navigator.userAgent;g&&null!=g&&"null"!=g&&0<g.length&&(g=g.replace("je=","_dummy="));null!=g&&"null"!=g&&(f+=g);a||(a=window.jcn.event);c||(c=window.jcn.revenue);b||(b=window.jcn.orderid);d||(d=window.jcn.var1);e||(e=window.jcn.var2);m||(m=window.jcn.var3);var h;window.jcn.conversionPage&&(h=window.jcn.conversionPage);f=f+"&joid="+b+"&jcv="+c+"&je="+a+"&uag="+
l;d&&(f=f+"&jvar1="+escape(d));e&&(f=f+"&jvar2="+escape(e));m&&(f=f+"&jvar3="+escape(m));a=new Image;a.src=f+"&jru="+h+jinfo;a.onload=function(){jVoid()}}function jVoid(){}var jLandEvtRec=!1;
function recJSLand(){var a,c,b,d,e=d="",m="",f="",g="",l=!1;if(0>jurlStr.indexOf("jkId=")&&0>jurlStr.indexOf("jtid=")&&0>jurlStr.indexOf("jsid=")){a=jAccountId;if(1==jCustParam&&void 0!=jurlStr&&null!=jurlStr&&""!=jurlStr)c=null==window.jPub||"undefined"==window.jPub?getQVar(jsrcp,jurlStr):window.jPub,d=null==window.jCampaign||"undefined"==window.jCampaign?getQVar(jcmp,jurlStr):window.jCampaign,b=getQVar(jmdp,jurlStr),e=null==window.jAdGroup||"undefined"==window.jAdGroup?getQVar(jagp,jurlStr):window.jAdGroup,
m=null==window.jkwd||"undefined"==window.jkwd?getQVar(jkp,jurlStr):window.jkwd,f=getQVar(jmtp,jurlStr),g=getQVar(jadp,jurlStr);else if(1==jtrkOrg){var h=getwdom().substr(1),k=document.referrer;if("undefined"!=k&&null!=k&&0<k.length){var n=k;0<n.indexOf("?")&&(n=k.substr(0,n.indexOf("?")));0>n.indexOf(h)&&(b="seo",d="SEO Campaign",c=jSEOName,l=!0)}else 1!=jtrkDir||null!=k&&0!=k.length&&k!=window.location||(h=""+jgetck(jckName),null!=h&&"null"!=h&&""!=h&&void 0!=h)||(b="direct",d=jDirCampName,c=jSEOName,
l=!0)}jurlStr="jt=1&jaid="+a+"&jm="+b+"&jsrc="+c+"&jcp="+d+"&jag="+e+"&jk="+m+"&jmt="+f+"&jcr="+g+"&isseo="+l}if(-1!=jurlStr.indexOf("jsid=")||-1!=jurlStr.indexOf("jtid=")||-1!=jurlStr.indexOf("jkId=")||null!=a&&void 0!=a&&void 0!=c&&""!=c)if(sfcData=jurlStr,jexecLngCode=!0,a=escape(document.referrer),c=escape(window.location),-1!=sfcData.indexOf("jtest=")&&(a=escape(window.location)),-1!=jurlStr.indexOf("jcid="))jsetck(jurlStr);else{d="";b=0;(e=""+jgetck(jckName))&&null!=e&&"null"!=e&&0<e.length&&
(d=getQVar("jcid",e));if(""==d||"null"==d||null==d)d=genuid(),b=1;d=sfcData+"&jcid="+d;jsetck(d);e="http";"https:"==window.location.protocol&&(e="https");a=e+track_URL+"je=landing&"+d+"&jru="+a+"&jlp="+c+"&jnv="+b+jinfo;c=new Image;c.src=a;c.onload=function(){jVoid()};jLandEvtRec=!0}}
function recPgView(){var a=""+jgetck(jckName);if(null!=a&&"null"!=a&&0!=a.length){var c=""+jgetck("sf_sess"),b=new Date;b.setMinutes(b.getMinutes()+30);if(null==c||"null"==c||0==c.length||1==jLandEvtRec)c=genuid()+"."+b.getMonth()+b.getDate()+b.getFullYear()+b.getHours()+b.getMinutes();document.cookie="sf_sess="+c+(b?";expires="+b.toGMTString():"")+";path=/";var b=escape(document.referrer),d=escape(window.location),e="http";"https:"==window.location.protocol&&(e="https");a=e+pageAction_URL+"je=jSiteAnalytics&jru="+
d+"&jpg="+b+"&uag="+navigator.userAgent+jinfo+"&"+a+"&jil="+jLandEvtRec+"&jsess="+c;c=new Image;c.src=a;c.onload=function(){jVoid()}}}
function getExInfo(){try{var a=window.screen.width+"x"+window.screen.height+"x"+window.screen.colorDepth,c=[],b=navigator.plugins;if(b&&0<b.length)for(var d=0;d<b.length;d++){var e=b[d];if(e){var m=e.filename.replace(/\.(plugin|dll)$/i,""),f=e.description,g=e.name,l=(f.match(/\d/g)||[]).join(""),h=(g.match(/\d/g)||[]).join("");c.push(m+","+(l.length>h.length?l:h))}}else for(b=["ShockwaveFlash.ShockwaveFlash","AcroPDF.PDF","AgControl.AgControl","wmplayer.ocx","QuickTime.QuickTime"],p=0;p<b.length;p++)try{d=
new ActiveXObject(b[p]);f="";try{f=d.GetVariable("$version")}catch(q){try{f=d.GetVersions()}catch(r){}}l=f?(f.match(/\d/g)||[]).join(""):"";c.push(b[p]+","+l)}catch(q){}var f=jcexpire,k=c.join(";"),n=navigator.language?navigator.language:"";infoStr=a+escape(k).replace(/\+/g,"%2B")+n+navigator.userAgent;jinfo="&ssc="+a+"&splu="+escape(k).replace(/\+/g,"%2B")+"&slg="+n+"&sce="+navigator.cookieEnabled+"&scd="+f}catch(q){infoStr=jinfo=""}}
var track_URL="://sftrack.searchforce.net/SFConversionTracking/img.jpg?",pageAction_URL="://sftrack.searchforce.net/SFConversionTracking/pa.jpg?",jckName="sf_conv_info",jCustParam=!1,jtrkOrg=!1,jtrkDir=!1,jSEOName="SEO",jDirCampName="Direct Traffic",sfcData,jurlStr,jcexpire,jAccountId,jsrcp,jcmp,jagp,jkp,jadp,jmtp,jmdp,jinfo,infoStr;
(function(){getExInfo();jLandEvtRec=!1;void 0!=window.jed&&"landing"===window.jed.event&&(void 0!=window.jstaticurl?jurlStr=window.jstaticurl:(jurlStr=""+window.location.hash+window.location.search,jurlStr=jurlStr.substring(jurlStr.indexOf("?")+1)),jAccountId=window.jed.accountid,jcexpire=window.jed.cookieexpire,void 0!=window.jed.trackseo&&1==window.jed.trackseo&&trackSEO(window.jed.seopublisher),void 0!=window.jed.trackdirect&&1==window.jed.trackdirect&&trackDirectTraffic(window.jed.directcampaign),
void 0!=window.jed.customparams&&1==window.jed.customparams&&(useCustomParams(),jsrcp=window.jed.sourceParam,jcmp=window.jed.campaignParam,jagp=window.jed.adgroupParam,jkp=window.jed.keywordParam,jadp=window.jed.creativeParam,jmtp=window.jed.matchTypeParam,jmdp=window.jed.mediumParam),(jurlStr&&null!=jurlStr&&"null"!=jurlStr&&0<jurlStr.length||1==jtrkOrg||1==jtrkDir)&&recJSLand());void 0==window.jcn||void 0!=window.jcn.tracklink&&0!=window.jcn.tracklink||recordJSConversion();void 0!=window.jed&&void 0!=
window.jed.trackSite&&1==window.jed.trackSite&&recPgView()})();